### ISSUE TITLE
Test dataset is not welformed

### ISSUE THREAD

**Issue by cedrikv** [OnroerendErfgoed/oe-inspire#2]
> 1. Het XML document is nog niet "wellformed". Dit betekent dat het geen gelding XML syntax heeft. 

>>row 55, 108, etc.- End tag name 'gml:surfaceMember' does not match start tag name 'gml:MultiSurface'.   >> end tag verwijderen. In het algemeent zorgen dat de tags correct genest zijn en dat elke tag die wordt geopend, ook gesloten wordt. 

>2. Het document valideert ook niet (XML Schema validatie volgens de schema's in die correct zijn gerefereerd in xsi:schemaLocation) 

>>row18- Attribute 'gml:id' is not allowed in element <wfs:FeatureCollection>  >> hier het attribuut gml:id verwijderen 

>Zodra dit in orde is gebracht, zullen jullie wellicht een geldige dataset hebben. Jullie kunnen deze zelf valideren met deze validator: 
http://inspire-sandbox.jrc.ec.europa.eu/validator/

**Comment by steuraa** [comment]
Fixed, validating properly according to the provided validator
